<?php
/**
 * @category    design
 * @package     default_default
 * @author      Daniel Rose <dr@intersales.de>
 */
?>
<?php /** @var $this Mage_Core_Block_Template */ ?>
<div class="login-container">
	<div class="login-box">
		<div class="login-form">
			<h1><?php echo $this->__('MageFontello Setup') ?></h1>
			<?php echo $this->getMessagesBlock()->toHtml() ?>
		</div>
		<p class="legal"><?php echo $this->__('Magento is a trademark of Magento Inc. Copyright &copy; %s Magento Inc.', date('Y')) ?></p>
		<div class="bottom"></div>
	</div>
</div>